"""New Migration

Revision ID: 5b39b95a81d8
Revises: 3934f43cdcd8
Create Date: 2023-06-03 18:13:05.164645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b39b95a81d8'
down_revision = '3934f43cdcd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
